---
# tasks file for om2m

#  git checkout om2m source
- name: git checkout om2m source
  git:
    repo: https://git.eclipse.org/r/om2m/org.eclipse.om2m
    dest: /opt/om2m/

# build source files
- name: build source files.
  shell: /bin/bash -lc "mvn clean install"
  args:
    chdir: /opt/om2m/
